In [1]:
import pandas as pd
import numpy as np
from matplotlib import *
from matplotlib import pyplot as plt
%matplotlib inline


In [2]:
d1= pd.read_csv("chennaihousepriceprediction.csv")
d1.head()

PRT_ID        AREA  INT_SQFT  DIST_MAINROAD  N_BEDROOM  N_BATHROOM  N_ROOM  \
0  P03210  Karapakkam      1004            131        1.0         1.0       3   
1  P09411  Anna Nagar      1986             26        2.0         1.0       5   
2  P01812       Adyar       909             70        1.0         1.0       3   
3  P05346   Velachery      1855             14        3.0         2.0       5   
4  P06210  Karapakkam      1226             84        1.0         1.0       3   

  SALE_COND PARK_FACIL   BUILDTYPE UTILITY_AVAIL  STREET MZZONE  QS_ROOMS  \
0  AbNormal        Yes  Commercial        AllPub   Paved      A       4.0   
1  AbNormal         No  Commercial        AllPub  Gravel     RH       4.9   
2  AbNormal        Yes  Commercial           ELO  Gravel     RL       4.1   
3    Family         No      Others       NoSewr    Paved      I       4.7   
4  AbNormal        Yes      Others        AllPub  Gravel      C       3.0   

   QS_BATHROOM  QS_BEDROOM  QS_OVERALL  COMMIS  SALES_PRICE  
0          3.9         4.9       4.330  144400      7600000  
1          4.2         2.5       3.765  304049     21717770  
2          3.8         2.2       3.090   92114     13159200  
3          3.9         3.6       4.010   77042      9630290  
4          2.5         4.1       3.290   74063      7406250

In [3]:
d1.shape

(7109, 19)

In [4]:
d1.groupby('AREA')['AREA'].agg('count')

AREA
Adyar          773
Adyr             1
Ana Nagar        3
Ann Nagar        2
Anna Nagar     783
Chormpet         6
Chrmpet          6
Chrompet      1681
Chrompt          9
KK Nagar       996
KKNagar          1
Karapakam        3
Karapakkam    1363
T Nagar        496
TNagar           5
Velachery      979
Velchery         2
Name: AREA, dtype: int64

In [5]:
d2=d1.drop(['DIST_MAINROAD','SALE_COND','SALE_COND','UTILITY_AVAIL','MZZONE','COMMIS','PARK_FACIL'],axis='columns')
d2.head()

PRT_ID        AREA  INT_SQFT  N_BEDROOM  N_BATHROOM  N_ROOM   BUILDTYPE  \
0  P03210  Karapakkam      1004        1.0         1.0       3  Commercial   
1  P09411  Anna Nagar      1986        2.0         1.0       5  Commercial   
2  P01812       Adyar       909        1.0         1.0       3  Commercial   
3  P05346   Velachery      1855        3.0         2.0       5      Others   
4  P06210  Karapakkam      1226        1.0         1.0       3      Others   

   STREET  QS_ROOMS  QS_BATHROOM  QS_BEDROOM  QS_OVERALL  SALES_PRICE  
0   Paved       4.0          3.9         4.9       4.330      7600000  
1  Gravel       4.9          4.2         2.5       3.765     21717770  
2  Gravel       4.1          3.8         2.2       3.090     13159200  
3   Paved       4.7          3.9         3.6       4.010      9630290  
4  Gravel       3.0          2.5         4.1       3.290      7406250

In [6]:
d2.isnull().sum()

PRT_ID          0
AREA            0
INT_SQFT        0
N_BEDROOM       1
N_BATHROOM      5
N_ROOM          0
BUILDTYPE       0
STREET          0
QS_ROOMS        0
QS_BATHROOM     0
QS_BEDROOM      0
QS_OVERALL     48
SALES_PRICE     0
dtype: int64

In [7]:
d3=d2.dropna()
d3.isnull().sum()

PRT_ID         0
AREA           0
INT_SQFT       0
N_BEDROOM      0
N_BATHROOM     0
N_ROOM         0
BUILDTYPE      0
STREET         0
QS_ROOMS       0
QS_BATHROOM    0
QS_BEDROOM     0
QS_OVERALL     0
SALES_PRICE    0
dtype: int64

In [8]:
d3.shape

(7056, 13)

In [9]:
d3['AREA'].unique()

array(['Karapakkam', 'Anna Nagar', 'Adyar', 'Velachery', 'Chrompet',
       'KK Nagar', 'TNagar', 'T Nagar', 'Chrompt', 'Chrmpet', 'Karapakam',
       'Ana Nagar', 'Chormpet', 'Adyr', 'Velchery', 'Ann Nagar',
       'KKNagar'], dtype=object)

In [10]:
d3['INT_SQFT'].unique()

array([1004, 1986,  909, ...,  688, 2051,  598], dtype=int64)

In [11]:

area = d3.AREA.unique()
area


array(['Karapakkam', 'Anna Nagar', 'Adyar', 'Velachery', 'Chrompet',
       'KK Nagar', 'TNagar', 'T Nagar', 'Chrompt', 'Chrmpet', 'Karapakam',
       'Ana Nagar', 'Chormpet', 'Adyr', 'Velchery', 'Ann Nagar',
       'KKNagar'], dtype=object)

In [12]:
for i in ['Ana Nagar','Ann Nagar']:
    d3['AREA']=d3['AREA'].replace(i,'Anna Nagar')
for i in ['Chrompt','Chrmpet','Chormpet']:
    d3['AREA']=d3['AREA'].replace(i,'Chrompet')
for i in ['Adyr']:
    d3['AREA']=d3['AREA'].replace(i,'Adyar')
for i in ['KKNagar']:
    d3['AREA']=d3['AREA'].replace(i,'KK Nagar')
for i in ['TNagar']:
    d3['AREA']=d3['AREA'].replace(i,'T Nagar')
for i in ['Velchery']:
    d3['AREA']=d3['AREA'].replace(i,'Velachery')
for i in ['Karapakam']:
    d3['AREA']=d3['AREA'].replace(i,'Karapakkam')
        

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documen

In [13]:
d3.AREA.unique()


array(['Karapakkam', 'Anna Nagar', 'Adyar', 'Velachery', 'Chrompet',
       'KK Nagar', 'T Nagar'], dtype=object)

In [14]:
d3.head()

PRT_ID        AREA  INT_SQFT  N_BEDROOM  N_BATHROOM  N_ROOM   BUILDTYPE  \
0  P03210  Karapakkam      1004        1.0         1.0       3  Commercial   
1  P09411  Anna Nagar      1986        2.0         1.0       5  Commercial   
2  P01812       Adyar       909        1.0         1.0       3  Commercial   
3  P05346   Velachery      1855        3.0         2.0       5      Others   
4  P06210  Karapakkam      1226        1.0         1.0       3      Others   

   STREET  QS_ROOMS  QS_BATHROOM  QS_BEDROOM  QS_OVERALL  SALES_PRICE  
0   Paved       4.0          3.9         4.9       4.330      7600000  
1  Gravel       4.9          4.2         2.5       3.765     21717770  
2  Gravel       4.1          3.8         2.2       3.090     13159200  
3   Paved       4.7          3.9         3.6       4.010      9630290  
4  Gravel       3.0          2.5         4.1       3.290      7406250

In [15]:
d3.AREA.unique()

array(['Karapakkam', 'Anna Nagar', 'Adyar', 'Velachery', 'Chrompet',
       'KK Nagar', 'T Nagar'], dtype=object)

In [16]:
d3['BATHROOMS']=d3['N_BEDROOM']+d3['N_BATHROOM']
d3.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


PRT_ID        AREA  INT_SQFT  N_BEDROOM  N_BATHROOM  N_ROOM   BUILDTYPE  \
0  P03210  Karapakkam      1004        1.0         1.0       3  Commercial   
1  P09411  Anna Nagar      1986        2.0         1.0       5  Commercial   
2  P01812       Adyar       909        1.0         1.0       3  Commercial   
3  P05346   Velachery      1855        3.0         2.0       5      Others   
4  P06210  Karapakkam      1226        1.0         1.0       3      Others   

   STREET  QS_ROOMS  QS_BATHROOM  QS_BEDROOM  QS_OVERALL  SALES_PRICE  \
0   Paved       4.0          3.9         4.9       4.330      7600000   
1  Gravel       4.9          4.2         2.5       3.765     21717770   
2  Gravel       4.1          3.8         2.2       3.090     13159200   
3   Paved       4.7          3.9         3.6       4.010      9630290   
4  Gravel       3.0          2.5         4.1       3.290      7406250   

   BATHROOMS  
0        2.0  
1        3.0  
2        2.0  
3        5.0  
4        2.0

In [17]:
d4=d3.drop(['N_BEDROOM','N_BATHROOM','STREET','PRT_ID','BUILDTYPE','QS_ROOMS','QS_BATHROOM','QS_BEDROOM'],axis='columns')
d4

AREA  INT_SQFT  N_ROOM  QS_OVERALL  SALES_PRICE  BATHROOMS
0     Karapakkam      1004       3       4.330      7600000        2.0
1     Anna Nagar      1986       5       3.765     21717770        3.0
2          Adyar       909       3       3.090     13159200        2.0
3      Velachery      1855       5       4.010      9630290        5.0
4     Karapakkam      1226       3       3.290      7406250        2.0
...          ...       ...     ...         ...          ...        ...
7104  Karapakkam       598       2       2.520      5353000        2.0
7105   Velachery      1897       5       3.920     10818480        5.0
7106   Velachery      1614       4       3.840      8351410        3.0
7107  Karapakkam       787       2       4.160      8507000        2.0
7108   Velachery      1896       5       3.640      9976480        5.0

[7056 rows x 6 columns]

In [18]:
d5=d4.rename(columns={"N_ROOM":"BHK"})
d5

AREA  INT_SQFT  BHK  QS_OVERALL  SALES_PRICE  BATHROOMS
0     Karapakkam      1004    3       4.330      7600000        2.0
1     Anna Nagar      1986    5       3.765     21717770        3.0
2          Adyar       909    3       3.090     13159200        2.0
3      Velachery      1855    5       4.010      9630290        5.0
4     Karapakkam      1226    3       3.290      7406250        2.0
...          ...       ...  ...         ...          ...        ...
7104  Karapakkam       598    2       2.520      5353000        2.0
7105   Velachery      1897    5       3.920     10818480        5.0
7106   Velachery      1614    4       3.840      8351410        3.0
7107  Karapakkam       787    2       4.160      8507000        2.0
7108   Velachery      1896    5       3.640      9976480        5.0

[7056 rows x 6 columns]

In [19]:
d5['PRICE_PERSQFT']=d4['SALES_PRICE']/d4['INT_SQFT']
d5.head()

AREA  INT_SQFT  BHK  QS_OVERALL  SALES_PRICE  BATHROOMS  \
0  Karapakkam      1004    3       4.330      7600000        2.0   
1  Anna Nagar      1986    5       3.765     21717770        3.0   
2       Adyar       909    3       3.090     13159200        2.0   
3   Velachery      1855    5       4.010      9630290        5.0   
4  Karapakkam      1226    3       3.290      7406250        2.0   

   PRICE_PERSQFT  
0    7569.721116  
1   10935.433031  
2   14476.567657  
3    5191.530997  
4    6040.986949

In [20]:
d6=d5[~(d5['INT_SQFT']/d5['BHK']<300)]

In [21]:
d6

AREA  INT_SQFT  BHK  QS_OVERALL  SALES_PRICE  BATHROOMS  \
0     Karapakkam      1004    3       4.330      7600000        2.0   
1     Anna Nagar      1986    5       3.765     21717770        3.0   
2          Adyar       909    3       3.090     13159200        2.0   
3      Velachery      1855    5       4.010      9630290        5.0   
4     Karapakkam      1226    3       3.290      7406250        2.0   
...          ...       ...  ...         ...          ...        ...   
7103  Karapakkam      1462    4       3.240      9387250        4.0   
7105   Velachery      1897    5       3.920     10818480        5.0   
7106   Velachery      1614    4       3.840      8351410        3.0   
7107  Karapakkam       787    2       4.160      8507000        2.0   
7108   Velachery      1896    5       3.640      9976480        5.0   

      PRICE_PERSQFT  
0       7569.721116  
1      10935.433031  
2      14476.567657  
3       5191.530997  
4       6040.986949  
...             ...  
7103    6420.827633  
7105    5702.941487  
7106    5174.355638  
7107   10809.402795  
7108    5261.856540  

[6565 rows x 7 columns]

In [22]:
d7=d6.sort_values('AREA')

In [23]:
d7

AREA  INT_SQFT  BHK  QS_OVERALL  SALES_PRICE  BATHROOMS  \
1705      Adyar       994    3        3.25     10834880        2.0   
5747      Adyar       966    3        2.89     12584475        2.0   
5746      Adyar      1197    3        2.95      8116035        2.0   
3009      Adyar      1192    3        2.55      7006800        2.0   
3008      Adyar       614    2        4.01      5720630        2.0   
...         ...       ...  ...         ...          ...        ...   
2465  Velachery      1929    5        4.33      7931560        5.0   
2466  Velachery      1820    5        3.26      9606220        5.0   
2475  Velachery      1877    5        2.92      8812240        5.0   
5778  Velachery      1630    4        3.30      8689410        3.0   
7108  Velachery      1896    5        3.64      9976480        5.0   

      PRICE_PERSQFT  
1705   10900.281690  
5747   13027.406832  
5746    6780.313283  
3009    5878.187919  
3008    9316.986971  
...             ...  
2465    4111.747019  
2466    5278.142857  
2475    4694.853490  
5778    5330.926380  
7108    5261.856540  

[6565 rows x 7 columns]

In [24]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
d7['AREA_NO']=le.fit_transform(d7['AREA'])

In [25]:
lst = dict(zip(d7.AREA,d7.AREA_NO))
lst

{'Adyar': 0,
 'Anna Nagar': 1,
 'Chrompet': 2,
 'KK Nagar': 3,
 'Karapakkam': 4,
 'T Nagar': 5,
 'Velachery': 6}

In [26]:
d7.head(20)

AREA  INT_SQFT  BHK  QS_OVERALL  SALES_PRICE  BATHROOMS  PRICE_PERSQFT  \
1705  Adyar       994    3        3.25     10834880        2.0   10900.281690   
5747  Adyar       966    3        2.89     12584475        2.0   13027.406832   
5746  Adyar      1197    3        2.95      8116035        2.0    6780.313283   
3009  Adyar      1192    3        2.55      7006800        2.0    5878.187919   
3008  Adyar       614    2        4.01      5720630        2.0    9316.986971   
1537  Adyar       995    3        2.95     12171985        2.0   12233.150754   
6738  Adyar      1223    4        4.09      8636890        4.0    7062.052330   
1535  Adyar      1277    4        4.01     13606320        4.0   10654.909945   
1531  Adyar       706    2        4.22      5054675        2.0    7159.596317   
680   Adyar       626    2        3.59      8173180        2.0   13056.198083   
2508  Adyar      1217    4        4.17     11226890        4.0    9225.053410   
2509  Adyar      1209    4        4.50      7466370        4.0    6175.657568   
3000  Adyar      1223    4        2.55     10978600        4.0    8976.778414   
2998  Adyar      1132    3        2.99      6380465        2.0    5636.453180   
4358  Adyar      1098    3        2.59      9647855        2.0    8786.753188   
6732  Adyar      1082    3        3.40     15242220        2.0   14087.079482   
1521  Adyar      1252    4        2.44      8529780        4.0    6812.923323   
3550  Adyar       658    2        3.17      4479770        2.0    6808.161094   
6729  Adyar       711    2        2.84      8394815        2.0   11807.053446   
694   Adyar       615    2        4.15      7700720        2.0   12521.495935   

      AREA_NO  
1705        0  
5747        0  
5746        0  
3009        0  
3008        0  
1537        0  
6738        0  
1535        0  
1531        0  
680         0  
2508        0  
2509        0  
3000        0  
2998        0  
4358        0  
6732        0  
1521        0  
3550        0  
6729        0  
694         0

In [27]:
import matplotlib.pyplot as plt


In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(d7[['AREA_NO','INT_SQFT','BHK','BATHROOMS']],d7[['SALES_PRICE']],test_size=0.2,random_state=10)

In [29]:
x_test,y_test

(      AREA_NO  INT_SQFT  BHK  BATHROOMS
 5664        3      1719    4        3.0
 6226        3      2058    6        6.0
 6980        2      1177    3        2.0
 6423        5      1954    5        3.0
 1714        3      1425    4        3.0
 ...       ...       ...  ...        ...
 4562        4       818    2        2.0
 4177        5      1672    4        2.0
 543         6      1686    4        3.0
 6365        4      1358    4        4.0
 3187        4       651    2        2.0
 
 [1313 rows x 4 columns],       SALES_PRICE
 5664     15598600
 6226     17076900
 6980     12335950
 6423     14885280
 1714      9762100
 ...           ...
 4562      7197750
 4177     18911110
 543      10094840
 6365      7130000
 3187      6581500
 
 [1313 rows x 1 columns])

In [30]:
x_train, y_train

(      AREA_NO  INT_SQFT  BHK  BATHROOMS
 309         4      1188    3        2.0
 378         3      1941    5        5.0
 5315        6      1884    5        5.0
 1378        5      1782    4        2.0
 4715        1      2000    5        3.0
 ...       ...       ...  ...        ...
 493         1      1877    5        3.0
 6299        3      2016    5        5.0
 6546        1      1968    5        3.0
 1481        4      1034    3        2.0
 4587        1      1744    4        2.0
 
 [5252 rows x 4 columns],       SALES_PRICE
 309       9819500
 378      12228420
 5315     16515880
 1378     12105050
 4715     16859010
 ...           ...
 493      13064510
 6299     11374960
 6546     22579530
 1481      6117000
 4587     14155830
 
 [5252 rows x 1 columns])

In [31]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
lr_clf=KNeighborsRegressor()


In [32]:
lr_clf.fit(d7[['AREA_NO','INT_SQFT','BHK','BATHROOMS']],d7[['SALES_PRICE']])


KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                    weights='uniform')

In [33]:
lr_clf.score(d7[['AREA_NO','INT_SQFT','BHK','BATHROOMS']],d7[['SALES_PRICE']])

0.6299453335505126

In [34]:
lr_clf.predict([[1,1100,3,2]])

array([[11148249.]])

In [35]:
lr_clf.predict([[6,1100,3,3]])

array([[6024225.]])

In [36]:
import pickle

In [37]:
with open('housepredictionpickle.pickle', 'wb') as f:
    pickle.dump(lr_clf,f)

In [38]:
with open('housepredictionpickle.pickle', 'rb') as f:
    model = pickle.load(f)

In [39]:
model.predict([[1,1800,3,2]])

array([[14625816.]])

model.predict([[3,1344,3]])

In [40]:
model.predict([[3,1500,3,3]])

array([[10880956.]])